### ISSUE TITLE
Import error on Blender 3.3

### ISSUE THREAD

**Issue by Mortgar** [arcanxeros/doublefine_mesh_import#1]
Not sure what caused this but I unpacked the files and tried to import the headbanger model and got this error.
![blender error](https://user-images.githubusercontent.com/103344395/211161166-7d9f2206-1132-4b72-a4db-e9ff04f6c859.png)

**Comment by Tannister** [comment]
Yeah so on Blender 3.4 the headbanger model imports fine

My guess is that something changed in Blender's API between v3.3 & v3.4
I'll take a look to see if i can make it work on both versions, otherwise i will indicate that the plugin is for Blender 3.4+

![image](https://user-images.githubusercontent.com/36128673/211161307-4e69fcc9-1214-4ace-bbbb-19083c16e02c.png)

**Comment by Mortgar** [comment]
So I tried importing it on 3.4 and I got this error, maybe the unpacker I used messed up along the way
![image](https://user-images.githubusercontent.com/103344395/211162357-d44ac0b0-d320-4707-a22b-50d9d88d7171.png)

**Comment by Tannister** [comment]
I've found the actual issue i think:

if i'm correct, you are trying to import the mesh without the rig files

Due to a oversight on my end, the import fails.

**Comment by Mortgar** [comment]
Yeah that's what was happening, thanks for the help I greatly appreciate it.
